CREATE TABLE T_USER
(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE T_MEMEBER
(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  LAST_NAME VARCHAR(50),
  FIRST_NAME VARCHAR(50),
  CHINESS_LAST_NAME VARCHAR(50),
  CHINESS_FIRST_NAME VARCHAR(50),
  INTRODUCER_NAME VARCHAR(50),
  MEMBERSHIP_ACQUISITION_DATE DATE,
  MEMBERSHIP_ACQUISITION_TEMPLE_CODE VARCHAR(3),
  MEMBERSHIP_ACQUISITION_CITY_CODE VARCHAR(3),
  MEMBER_PURIFICATION_DATE DATE,
  MEMBER_FAMILY_TEMPLE_DATE DATE,
  MASTER_NAME VARCHAR(50),
  GUARANTOR_NAME VARCHAR(100),
  GROUP_NUMBER INTEGER,
  DOB DATE,
  LAST_UPDATE_USER_ID INTEGER,
  LAST_UDPATE_DATE DATE
);
CREATE INDEX I_MEMBER_LAST_NAME__FIRST_NAME ON T_MEMEBER(LAST_NAME, FIRST_NAME);

